// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: games.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, level, status)
VALUES ($1, $2, $3)
RETURNING id, code, level, status, created_at, updated_at
`

type CreateGameParams struct {
	Code   string
	Level  string
	Status string
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.Code, arg.Level, arg.Status)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByCode = `-- name: GetGameByCode :one
SELECT id, code, level, status, created_at, updated_at FROM games
WHERE code = $1
`

func (q *Queries) GetGameByCode(ctx context.Context, code string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByCode, code)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByGameCodeAndID = `-- name: GetPlayerByGameCodeAndID :one
SELECT p.id, p.game_id, p.nickname, p.is_host, p.joined_at FROM players AS p 
JOIN games AS g ON g.id = p.game_id
WHERE g.code = $1 AND p.id = $2
`

type GetPlayerByGameCodeAndIDParams struct {
	Code string
	ID   int64
}

func (q *Queries) GetPlayerByGameCodeAndID(ctx context.Context, arg GetPlayerByGameCodeAndIDParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByGameCodeAndID, arg.Code, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Nickname,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games SET status = $2 WHERE id = $1
`

type UpdateGameStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.Exec(ctx, updateGameStatus, arg.ID, arg.Status)
	return err
}
