// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID        int64
	Code      string
	Level     string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Player struct {
	ID       int64
	GameID   int64
	Nickname string
	IsHost   pgtype.Bool
	JoinedAt pgtype.Timestamptz
}

type Question struct {
	ID        int64
	Level     string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Round struct {
	ID               int64
	GameID           int64
	QuestionID       pgtype.Int8
	QuestionPlayerID int64
	IsJoker          pgtype.Bool
	Status           string
	CreatedAt        pgtype.Timestamptz
	Answer           pgtype.Text
	AnswerPlayerID   pgtype.Int8
	Deck             []string
}
