// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: players.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayersInGame = `-- name: CountPlayersInGame :one
SELECT COUNT(*) FROM players WHERE game_id = $1
`

func (q *Queries) CountPlayersInGame(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayersInGame, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players(game_id, nickname, is_host)
VALUES ($1, $2, $3)
RETURNING id, nickname, is_host, joined_at
`

type CreatePlayerParams struct {
	GameID   int64
	Nickname string
	IsHost   pgtype.Bool
}

type CreatePlayerRow struct {
	ID       int64
	Nickname string
	IsHost   pgtype.Bool
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.GameID, arg.Nickname, arg.IsHost)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :one
DELETE FROM players 
WHERE id = $1 AND game_id = $2
RETURNING id, nickname
`

type DeletePlayerParams struct {
	ID     int64
	GameID int64
}

type DeletePlayerRow struct {
	ID       int64
	Nickname string
}

func (q *Queries) DeletePlayer(ctx context.Context, arg DeletePlayerParams) (DeletePlayerRow, error) {
	row := q.db.QueryRow(ctx, deletePlayer, arg.ID, arg.GameID)
	var i DeletePlayerRow
	err := row.Scan(&i.ID, &i.Nickname)
	return i, err
}

const getFirstPlayerInGame = `-- name: GetFirstPlayerInGame :one
SELECT id FROM players
WHERE game_id = $1
ORDER BY joined_at ASC
LIMIT 1
`

func (q *Queries) GetFirstPlayerInGame(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getFirstPlayerInGame, gameID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, game_id, nickname, is_host, joined_at FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Nickname,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const getPlayerStatsByGameID = `-- name: GetPlayerStatsByGameID :many
SELECT
  p.id AS player_id,
  p.nickname,
  COUNT(CASE WHEN r.question_player_id = p.id THEN 1 END) AS questions_asked,
  COUNT(CASE WHEN r.answer_player_id = p.id THEN 1 END) AS questions_answered,
  COUNT(CASE WHEN r.answer_player_id = p.id AND r.is_joker = TRUE THEN 1 END) AS joker_cards_drawn
FROM players p
LEFT JOIN rounds r ON r.game_id = p.game_id
WHERE p.game_id = $1
GROUP BY p.id, p.nickname
ORDER BY p.id ASC
`

type GetPlayerStatsByGameIDRow struct {
	PlayerID          int64
	Nickname          string
	QuestionsAsked    int64
	QuestionsAnswered int64
	JokerCardsDrawn   int64
}

func (q *Queries) GetPlayerStatsByGameID(ctx context.Context, gameID int64) ([]GetPlayerStatsByGameIDRow, error) {
	rows, err := q.db.Query(ctx, getPlayerStatsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerStatsByGameIDRow
	for rows.Next() {
		var i GetPlayerStatsByGameIDRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Nickname,
			&i.QuestionsAsked,
			&i.QuestionsAnswered,
			&i.JokerCardsDrawn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersByGameCode = `-- name: ListPlayersByGameCode :many
SELECT p.id, p.nickname, p.is_host, p.joined_at
FROM players p
JOIN games g ON p.game_id = g.id
WHERE g.code = $1
ORDER BY p.joined_at
`

type ListPlayersByGameCodeRow struct {
	ID       int64
	Nickname string
	IsHost   pgtype.Bool
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) ListPlayersByGameCode(ctx context.Context, code string) ([]ListPlayersByGameCodeRow, error) {
	rows, err := q.db.Query(ctx, listPlayersByGameCode, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersByGameCodeRow
	for rows.Next() {
		var i ListPlayersByGameCodeRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.IsHost,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
