// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: questions.sql

package database

import (
	"context"
)

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT content FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var content string
	err := row.Scan(&content)
	return content, err
}

const getQuestionsByLevel = `-- name: GetQuestionsByLevel :many
SELECT id, content
FROM questions
WHERE level = $1
ORDER BY RANDOM()
LIMIT $2
`

type GetQuestionsByLevelParams struct {
	Level string
	Limit int32
}

type GetQuestionsByLevelRow struct {
	ID      int64
	Content string
}

func (q *Queries) GetQuestionsByLevel(ctx context.Context, arg GetQuestionsByLevelParams) ([]GetQuestionsByLevelRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsByLevel, arg.Level, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsByLevelRow
	for rows.Next() {
		var i GetQuestionsByLevelRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
