// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rounds.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRound = `-- name: CompleteRound :exec
UPDATE rounds
SET status = $2,
    is_joker = $3
WHERE id = $1
`

type CompleteRoundParams struct {
	ID      int64
	Status  string
	IsJoker pgtype.Bool
}

func (q *Queries) CompleteRound(ctx context.Context, arg CompleteRoundParams) error {
	_, err := q.db.Exec(ctx, completeRound, arg.ID, arg.Status, arg.IsJoker)
	return err
}

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (
  game_id, question_id, question_player_id, answer_player_id,deck, status
)
VALUES (
  $1, $2, $3, $4,$5, 'pending'
)
RETURNING id, question_id, question_player_id,answer_player_id, status
`

type CreateRoundParams struct {
	GameID           int64
	QuestionID       pgtype.Int8
	QuestionPlayerID int64
	AnswerPlayerID   pgtype.Int8
	Deck             []string
}

type CreateRoundRow struct {
	ID               int64
	QuestionID       pgtype.Int8
	QuestionPlayerID int64
	AnswerPlayerID   pgtype.Int8
	Status           string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (CreateRoundRow, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.GameID,
		arg.QuestionID,
		arg.QuestionPlayerID,
		arg.AnswerPlayerID,
		arg.Deck,
	)
	var i CreateRoundRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.QuestionPlayerID,
		&i.AnswerPlayerID,
		&i.Status,
	)
	return i, err
}

const finishRound = `-- name: FinishRound :exec
UPDATE rounds
SET status = 'done'
WHERE id = $1
`

func (q *Queries) FinishRound(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, finishRound, id)
	return err
}

const getCurrentRoundByGameCode = `-- name: GetCurrentRoundByGameCode :one
SELECT r.id, r.question_player_id, r.answer_player_id, r.question_id, r.is_joker, r.created_at, g.id AS game_id,
       r.status, g.level,
       q.content AS question_content
FROM rounds r
JOIN games g ON r.game_id = g.id
JOIN questions q ON r.question_id = q.id
WHERE g.code = $1
ORDER BY r.created_at DESC
LIMIT 1
`

type GetCurrentRoundByGameCodeRow struct {
	ID               int64
	QuestionPlayerID int64
	AnswerPlayerID   pgtype.Int8
	QuestionID       pgtype.Int8
	IsJoker          pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	GameID           int64
	Status           string
	Level            string
	QuestionContent  string
}

func (q *Queries) GetCurrentRoundByGameCode(ctx context.Context, code string) (GetCurrentRoundByGameCodeRow, error) {
	row := q.db.QueryRow(ctx, getCurrentRoundByGameCode, code)
	var i GetCurrentRoundByGameCodeRow
	err := row.Scan(
		&i.ID,
		&i.QuestionPlayerID,
		&i.AnswerPlayerID,
		&i.QuestionID,
		&i.IsJoker,
		&i.CreatedAt,
		&i.GameID,
		&i.Status,
		&i.Level,
		&i.QuestionContent,
	)
	return i, err
}

const getLatestRoundInGame = `-- name: GetLatestRoundInGame :one
SELECT id, game_id, question_id, question_player_id, is_joker, status, created_at, answer, answer_player_id, deck FROM rounds
WHERE game_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestRoundInGame(ctx context.Context, gameID int64) (Round, error) {
	row := q.db.QueryRow(ctx, getLatestRoundInGame, gameID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.QuestionPlayerID,
		&i.IsJoker,
		&i.Status,
		&i.CreatedAt,
		&i.Answer,
		&i.AnswerPlayerID,
		&i.Deck,
	)
	return i, err
}

const getRoundByID = `-- name: GetRoundByID :one
SELECT id, game_id, question_id, question_player_id, is_joker, status, created_at, answer, answer_player_id, deck FROM rounds WHERE id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByID, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.QuestionPlayerID,
		&i.IsJoker,
		&i.Status,
		&i.CreatedAt,
		&i.Answer,
		&i.AnswerPlayerID,
		&i.Deck,
	)
	return i, err
}

const getRoundSummaryByGameID = `-- name: GetRoundSummaryByGameID :many
SELECT
  r.id AS round_id,
  r.answer AS answer,
  r.is_joker,
  q.content AS question,
  qp.id AS question_player_id,
  qp.nickname AS question_player_nickname,
  ap.id AS answer_player_id,
  ap.nickname AS answer_player_nickname
FROM rounds r
JOIN questions q ON r.question_id = q.id
JOIN players qp ON r.question_player_id = qp.id
JOIN players ap ON r.answer_player_id = ap.id
WHERE r.game_id = $1
ORDER BY r.id ASC
`

type GetRoundSummaryByGameIDRow struct {
	RoundID                int64
	Answer                 pgtype.Text
	IsJoker                pgtype.Bool
	Question               string
	QuestionPlayerID       int64
	QuestionPlayerNickname string
	AnswerPlayerID         int64
	AnswerPlayerNickname   string
}

func (q *Queries) GetRoundSummaryByGameID(ctx context.Context, gameID int64) ([]GetRoundSummaryByGameIDRow, error) {
	rows, err := q.db.Query(ctx, getRoundSummaryByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoundSummaryByGameIDRow
	for rows.Next() {
		var i GetRoundSummaryByGameIDRow
		if err := rows.Scan(
			&i.RoundID,
			&i.Answer,
			&i.IsJoker,
			&i.Question,
			&i.QuestionPlayerID,
			&i.QuestionPlayerNickname,
			&i.AnswerPlayerID,
			&i.AnswerPlayerNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoundAnswer = `-- name: SetRoundAnswer :exec
UPDATE rounds
SET answer = $2
WHERE id = $1
`

type SetRoundAnswerParams struct {
	ID     int64
	Answer pgtype.Text
}

func (q *Queries) SetRoundAnswer(ctx context.Context, arg SetRoundAnswerParams) error {
	_, err := q.db.Exec(ctx, setRoundAnswer, arg.ID, arg.Answer)
	return err
}

const setRoundQuestionID = `-- name: SetRoundQuestionID :exec
UPDATE rounds
SET question_id = $2
WHERE id = $1
`

type SetRoundQuestionIDParams struct {
	ID         int64
	QuestionID pgtype.Int8
}

func (q *Queries) SetRoundQuestionID(ctx context.Context, arg SetRoundQuestionIDParams) error {
	_, err := q.db.Exec(ctx, setRoundQuestionID, arg.ID, arg.QuestionID)
	return err
}

const updateRoundStatus = `-- name: UpdateRoundStatus :exec
UPDATE rounds SET is_joker = $2, status = $3 WHERE id = $1
`

type UpdateRoundStatusParams struct {
	ID      int64
	IsJoker pgtype.Bool
	Status  string
}

func (q *Queries) UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error {
	_, err := q.db.Exec(ctx, updateRoundStatus, arg.ID, arg.IsJoker, arg.Status)
	return err
}
