version: "3.8"

services:
  db:
    container_name: "jokerDB"
    image: postgres:15-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "joker"
      POSTGRES_USER: "joker"
      POSTGRES_PASSWORD: "joker"
    restart: unless-stopped

 