// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feedback.sql

package sqlc

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :exec
INSERT INTO feedback (type, content)
VALUES ($1, $2)
`

type CreateFeedbackParams struct {
	Type    string
	Content string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) error {
	_, err := q.db.Exec(ctx, createFeedback, arg.Type, arg.Content)
	return err
}
