// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, status, updated_at)
VALUES($1, $2 , updated_at = NOW())
RETURNING id, code, status, created_at
`

type CreateGameParams struct {
	Code   string
	Status string
}

type CreateGameRow struct {
	ID        int64
	Code      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRow(ctx, createGame, arg.Code, arg.Status)
	var i CreateGameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
